### PR TITLE
PORISD-84: SimpleSAMLphp setup update.

### PR DESCRIPTION
**Pull request by tormi**
## Changes

- switch from committed SimpleSAMLphp files to Composer-based setup,
- security update for `simplesamlphp/simplesamlphp` package,
- introduce `lando provision` tool in the repo root folder, see the readme's last section.

Deployment needs nginx  setup provisioning for `/simplesaml` alias changes in all remote environments.

### CODE REVIEW

**Comment by tormi** [comment]
Local Metarefresh fetch in https://pori.lndo.site/simplesaml/module.php/metarefresh/fetch.php:

04:19:31.403Z [metarefresh]: Executing set [pori]
04:19:31.411Z [metarefresh]: In set [pori] loading source [https://fs.pori.fi/FederationMetadata/2007-06/FederationMetadata.xml]
04:19:31.736Z Writing: /app/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php
04:19:31.760Z Writing: /app/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-sp-remote.php

**Comment by tormi** [comment]
Metarefresh fetch gives permissions errors in `develop`:

https://pori.dev.wunder.io/simplesaml/module.php/metarefresh/fetch.php

```
09:30:14.892Z [metarefresh]: Executing set [pori]
09:30:14.892Z [metarefresh]: In set [pori] loading source [https://fs.pori.fi/FederationMetadata/2007-06/FederationMetadata.xml]
09:30:14.974Z Writing: /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php
09:30:14.975Z SimpleSAML\Error\Exception: Error 2 - rename(/var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php): failed to open stream: Permission denied at /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/System.php:227
09:30:14.975Z Backtrace:
09:30:14.975Z 6 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/www/_include.php:44 (SimpleSAML_error_handler)
09:30:14.975Z 5 [builtin] (rename)
09:30:14.975Z 4 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/System.php:227 (SimpleSAML\Utils\System::writeFile)
09:30:14.975Z 3 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/lib/MetaLoader.php:584 (SimpleSAML\Module\metarefresh\MetaLoader::writeMetadataFiles)
09:30:14.975Z 2 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/www/fetch.php:80 (require)
09:30:14.975Z 1 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
09:30:14.975Z 0 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/www/module.php:10 (N/A)
09:30:14.975Z SimpleSAML\Error\Exception: Error 2 - rename(/tmp/simplesaml/1129287649,/var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php): Permission denied at /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/System.php:227
09:30:14.975Z Backtrace:
09:30:14.975Z 6 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/www/_include.php:44 (SimpleSAML_error_handler)
09:30:14.975Z 5 [builtin] (rename)
09:30:14.975Z 4 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/System.php:227 (SimpleSAML\Utils\System::writeFile)
09:30:14.975Z 3 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/lib/MetaLoader.php:584 (SimpleSAML\Module\metarefresh\MetaLoader::writeMetadataFiles)
09:30:14.975Z 2 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/www/fetch.php:80 (require)
09:30:14.975Z 1 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
09:30:14.975Z 0 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/www/module.php:10 (N/A)
09:30:14.975Z SimpleSAML\Error\Exception: Error moving "/tmp/simplesaml/1129287649" to "/var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php": rename(/tmp/simplesaml/1129287649,/var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php): Permission denied
09:30:14.975Z Backtrace:
09:30:14.975Z 4 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/System.php:230 (SimpleSAML\Utils\System::writeFile)
09:30:14.975Z 3 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/lib/MetaLoader.php:584 (SimpleSAML\Module\metarefresh\MetaLoader::writeMetadataFiles)
09:30:14.975Z 2 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/www/fetch.php:80 (require)
09:30:14.975Z 1 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
09:30:14.975Z 0 /var/www/pori.dev.wunder.io/releases/1624868146/vendor/simplesamlphp/simplesamlphp/www/module.php:10 (N/A)
```

**Comment by tormi** [comment]
This works https://simplesamlphp.org/docs/stable/metarefresh:simplesamlphp-automated_metadata > 3 Testing it manually:

`cd /var/www/pori.dev.wunder.io/current/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/bin`
`./metarefresh.php -s https://fs.pori.fi/FederationMetadata/2007-06/FederationMetadata.xml`

**Comment by tormi** [comment]
Also, locally works: https://github.com/City-of-Pori/pori-kada/pull/418#issuecomment-862911181

**Comment by tormi** [comment]
I'm trying to change the `cron` user from `nginx` to `www-admin` here: https://github.com/City-of-Pori/pori-kada/commit/fa92f1853504278d55547ac72fa804cc039ecb9b

**Comment by tormi** [comment]
Looks like metarefresh process is done by `root` user:

```
[www-admin@develop-web1 ~]$ ls -la /tmp/simplesaml
total 4
drwx------   2 www-admin www-admin    6 Jun 29 13:33 .
drwxrwxrwt. 15 root      root      4096 Jun 29 14:16 ..
```

**Comment by tormi** [comment]
Pori SAML has 3 crons: daily, hourly & frequent: https://pori.dev.wunder.io/simplesaml/module.php/cron/croninfo.php `daily` & `frequent` are working fine, but `hourly` gives the permissions error: https://pori.dev.wunder.io/simplesaml/module.php/cron/cron.php?key=***&tag=hourly&output=xhtml

```
Cron did run tag [hourly] at Thu, 01 Jul 21 08:21:44 +0300
Error during metarefresh: Error moving "/tmp/simplesaml/237298746" to "/var/www/pori.dev.wunder.io/releases/1625115686/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php": rename(/tmp/simplesaml/237298746,/var/www/pori.dev.wunder.io/releases/1625115686/vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php): Permission denied
```

But it actually runs the cronjob and updates the metafile, `less vendor/simplesamlphp/simplesamlphp/metadata/metarefresh-pori/saml20-idp-remote.php` gives:

```
<?php
/* This file was generated by the metarefresh module at 2021-07-01T05:00:01Z
Do not update it manually as it will get overwritten
*/
```

**Review by operinko — COMMENTED** [review]
• start using SimpleSAMLphp Automated Metadata Management.
Pori already was using metarefresh in the old setup, so it's not so much "start using" than "continue using" :D

All in all though, without actually testing it at all, looks solid to me.

**Comment by tormi** [comment]
Thanks, Olli!

**Pull request merged**
