### PR TITLE
PORI-135 Slideshow to match design

### PR DESCRIPTION
**Pull request by teroelonen**
To test:

1. drush fra -y && drush cc all
2. Go to any attraction card and make sure the slideshow layout matches the designs.
3. Go to attraction card listing page and make sure each item has visible images and listing looks good.

Desktop design: https://drive.google.com/open?id=1_yY6yogj-ymzhbr49ZDnqg3vxyC0uGg2&authuser=0

Mobile design: https://drive.google.com/file/d/18U0JqCmH5TsgKZjy7nAUEydWceqBa5xb/view

### CODE REVIEW

**Comment by demoshane** [comment]
Checking

**Comment by demoshane** [comment]
Mobile view: https://monosnap.com/file/fg6I8Qo93iewzfZ0dcnKOHqQMYOYpa balloons have small grey blocks, seems to be this style (disabling removes the blocks) https://monosnap.com/file/3pe9MAyg03a35xeZPx4iJdgg7c9H5h

Desktop view seems to be along the designs.

Could you point me to attraction list page?

**Comment by teroelonen** [comment]
Fixed the issue with mobile view.
Here is attraction list page for example: https://local.visitpori.fi/nae-ja-koe/ostokset

**Comment by teroelonen** [comment]
screen shot 2018-04-11 at 11 32 08
It should look like this on mobile now.

**Comment by demoshane** [comment]
Rechecking

**Comment by demoshane** [comment]
Both listing page and mobile look good. Approved.

**Pull request merged**
