### PR TITLE
PORI-395 Carousel layout bug

### PR DESCRIPTION
**Pull request by teroelonen**
…th touchevents

To test:

1. drush cc all
2. Use the chrome inspector and pick a mobile phone from the select list. For example Pixel 2 and make sure the carousel works correctly.

### CODE REVIEW

**Comment by ZeiP** [comment]
Conflicts.

**Comment by teroelonen** [comment]
Fixed.

**Comment by ZeiP** [comment]
Unfortunately conflicting again :)

**Comment by teroelonen** [comment]
Fixed again :)

**Comment by teroelonen** [comment]
Fixed once again :)

**Review by ZeiP — APPROVED** [review]

**Pull request merged**
