### PR TITLE
PORI-62 Small lifup banner (also known as Rauma banner)

### PR DESCRIPTION
**Pull request by teroelonen**
To test:

1. drush fra -y && drush cc all
2. Go to edit any liftup and choose from liftup options "to small lifup banner". Also make sure the liftup is published.
3. Add four liftups this way and make sure some of them have internal links, external links and some without any links.
4. Go to front page and make sure there is a new banner just before footer that has these liftups you just added there.
5. Make sure the banner works responsively.

### CODE REVIEW

**Comment by teroelonen** [comment]
screen shot 2018-04-12 at 18 24 44

**Comment by demoshane** [comment]
Checking

**Comment by demoshane** [comment]
Seems to work as advertiset for logged in users (admin level tested). Anons however don't seem to see it.

**Comment by ZeiP** [comment]
Works in my local environment correctly. Merging, since this seems to be an environment-dependent problem.

**Pull request merged**
